##########################################################
#                                                        #
#                     DIGITIZER                          #
#                                                        #
##########################################################


/gate/digitizer/verbose 0
/gate/digitizer/Singles/insert adderCompton
/gate/digitizer/Singles/insert readout
/gate/digitizer/Singles/readout/setDepth 2

/gate/digitizer/Singles/insert blurring
/gate/digitizer/Singles/blurring/setResolution 0.18
/gate/digitizer/Singles/blurring/setEnergyOfReference 330. keV

/gate/digitizer/Singles/insert thresholder
/gate/digitizer/Singles/thresholder/setThreshold 200. keV
#/gate/digitizer/Singles/insert upholder
#/gate/digitizer/Singles/upholder/setUphold 650. keV

#/gate/digitizer/name Coincidences
#/gate/digitizer/insert coincidenceSorter
/gate/digitizer/Coincidences/setInputName Singles
/gate/digitizer/Coincidences/setWindow 5. ns
#/gate/digitizer/Coincidences/minSectorDifference 1
#/gate/digitizer/Coincidences/setDepth 1
/gate/digitizer/Coincidences/MultiplesPolicy takeAllGoods