# World

/gate/world/geometry/setXLength 150. cm
/gate/world/geometry/setYLength 150. cm
/gate/world/geometry/setZLength 100. cm
/gate/world/vis/setVisible 0

# Cylindrical PET

/gate/world/daughters/name cylindricalPET
/gate/world/daughters/insert cylinder
/gate/cylindricalPET/setMaterial Air
/gate/cylindricalPET/geometry/setRmax 575 mm
/gate/cylindricalPET/geometry/setRmin 425 mm
/gate/cylindricalPET/geometry/setHeight 500 mm
/gate/cylindricalPET/vis/forceWireframe
/gate/cylindricalPET/vis/setColor white
/gate/cylindricalPET/vis/setVisible 1

# rsector: red_module

/gate/cylindricalPET/daughters/name red_module
/gate/cylindricalPET/daughters/insert box
/gate/red_module/placement/setTranslation 0 486. 0 mm
/gate/red_module/geometry/setXLength 122. mm
/gate/red_module/geometry/setYLength 105 mm
/gate/red_module/geometry/setZLength 520 mm
/gate/red_module/setMaterial Air
/gate/red_module/vis/setColor red
/gate/red_module/vis/forceWireframe
/gate/red_module/vis/setVisible 1

# Module: artificial_module  

/gate/red_module/daughters/name artificial_module
/gate/red_module/daughters/insert box
/gate/artificial_module/placement/setTranslation 0 0 0 mm
/gate/artificial_module/geometry/setXLength 122. mm
/gate/artificial_module/geometry/setYLength 105 mm
/gate/artificial_module/geometry/setZLength 520 mm
/gate/artificial_module/setMaterial Air
/gate/artificial_module/vis/setColor red
/gate/artificial_module/vis/forceWireframe
/gate/artificial_module/vis/setVisible 1

# Scintillator layer 1

/gate/artificial_module/daughters/name scintillator_layer1
/gate/artificial_module/daughters/insert box
/gate/scintillator_layer1/placement/setTranslation 0 -14.5 0 mm
/gate/scintillator_layer1/geometry/setXLength 6 mm
/gate/scintillator_layer1/geometry/setYLength 24 mm
/gate/scintillator_layer1/geometry/setZLength 500 mm
/gate/scintillator_layer1/setMaterial EJ230
/gate/scintillator_layer1/vis/setColor white
/gate/scintillator_layer1/vis/forceWireframe
/gate/scintillator_layer1/vis/setVisible 1

# Scintillator layer 2

/gate/artificial_module/daughters/name scintillator_layer2
/gate/artificial_module/daughters/insert box
/gate/scintillator_layer2/placement/setTranslation 0 14.5 0 mm
/gate/scintillator_layer2/geometry/setXLength 6 mm
/gate/scintillator_layer2/geometry/setYLength 24 mm
/gate/scintillator_layer2/geometry/setZLength 500 mm
/gate/scintillator_layer2/setMaterial EJ230
/gate/scintillator_layer2/vis/setColor white
/gate/scintillator_layer2/vis/forceWireframe
/gate/scintillator_layer2/vis/setVisible 1

# repeat scintillators

/gate/scintillator_layer1/repeaters/insert cubicArray
/gate/scintillator_layer1/cubicArray/setRepeatNumberX 14
/gate/scintillator_layer1/cubicArray/setRepeatNumberY 1
/gate/scintillator_layer1/cubicArray/setRepeatNumberZ 1
/gate/scintillator_layer1/cubicArray/setRepeatVector 7 0 5 mm

/gate/scintillator_layer2/repeaters/insert cubicArray
/gate/scintillator_layer2/cubicArray/setRepeatNumberX 14
/gate/scintillator_layer2/cubicArray/setRepeatNumberY 1
/gate/scintillator_layer2/cubicArray/setRepeatNumberZ 1
/gate/scintillator_layer2/cubicArray/setRepeatVector 7 0 5 mm

# Wavelength shifters (WLS)

/gate/red_module/daughters/name wls
/gate/red_module/daughters/insert box
/gate/wls/placement/setTranslation 0 0 0 mm
/gate/wls/geometry/setXLength 100 mm
/gate/wls/geometry/setYLength 3 mm
/gate/wls/geometry/setZLength 10 mm
/gate/wls/setMaterial EJ230
/gate/wls/vis/setColor green
/gate/wls/vis/forceWireframe
/gate/wls/vis/setVisible 1

# Repeat WLS

/gate/wls/repeaters/insert cubicArray
/gate/wls/cubicArray/setRepeatNumberX 1
/gate/wls/cubicArray/setRepeatNumberY 1
/gate/wls/cubicArray/setRepeatNumberZ 50
/gate/wls/cubicArray/setRepeatVector 0 0 10 mm

# Repeat rsector

/gate/red_module/repeaters/insert ring
/gate/red_module/ring/setRepeatNumber 20

#	Repeat cylinder

/gate/cylindricalPET/repeaters/insert linear
/gate/cylindricalPET/linear/setRepeatVector 0. 0. 550. mm
/gate/cylindricalPET/linear/autoCenter true
/gate/cylindricalPET/linear/setRepeatNumber 3

# attach system

/gate/systems/cylindricalPET/rsector/attach box1
/gate/systems/cylindricalPET/crystal/attach box2
/gate/systems/cylindricalPET/crystal/attach 

# attach sensitive detector

/gate/scintillator_layer1/attachCrystalSD
/gate/scintillator_layer2/attachCrystalSD